import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ThemeProvider } from "@/components/theme-context";
import { getServerUser } from "@/lib/get-server-user";
import { getUserTheme } from "@/lib/theme";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = await getServerUser();
	const theme = user ? await getUserTheme(user.id) : "light";

	return (
		<html lang="en" data-theme={theme}>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-svh`}
			>
				<ThemeProvider initialTheme={theme}>
					<NuqsAdapter>
						<Navbar />
						{children}
					</NuqsAdapter>
				</ThemeProvider>
			</body>
		</html>
	);
}
